name: facebook_flutter_sdk
description: Flutter plugin for Facebook App Events, an app measurement
  solution that provides insight on app usage and user engagement in facebook pixel to optimize ads and measure the effectiveness of ad campaigns.
version: 1.0.0+1
homepage: https://github.com/oddbit/flutter_facebook_flutter_sdk

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.apparence.facebook_flutter_sdk
        pluginClass: FacebookAppEventsPlugin
      ios:
        pluginClass: FacebookAppEventsPlugin
